name: Generate Snake Animation
permissions:
  contents: write

on:
  schedule:
    - cron: "0 0 * * *"  # Menjalankan setiap hari pada pukul 00:00 UTC
  workflow_dispatch:  # Bisa dijalankan secara manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: RaisNafis
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake.gif

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -B output
          git add dist/github-contribution-grid-snake.*
          git commit -m "Updated Snake animation"
          git push -f origin output
