name: Update README with Wakatime Stats

on:
  schedule:
    - cron: "0 * * * *"  # Update setiap jam
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update Wakatime Stats
        run: |
          API_KEY="${{ secrets.WAKATIME_API_KEY }}"
          curl -o wakatime.svg "https://github-readme-stats.vercel.app/api/wakatime?api_key=$API_KEY&username=RaisNafis"

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add wakatime.svg
          git commit -m "Update Wakatime Stats"
          git push
